# Project information
site_name: Raymond Lau's Blog
site_description: Raymond Lau的个人博客
site_author: Raymond Lau
site_url: https://wendaojidian.github.io/Raymond


# Repository
repo_name: 'wendaojidian/Raymond.git'
repo_url: 'https://github.com/wendaojidian/Raymond.git'

# Copyright
copyright: "Copyright &copy; 2023 Fan Liu"


theme:
    name: material
    features:
        - navigations.tabs
        - navigations.sections
        - toc.integrate
        - navigation.top
        - search.suggest
        - search.highlight
        - content.tabs.link
        - content.code.annotation
        - content.code.copy
    palette:
        - scheme: default
          toggle:
            icon: material/toggle-switch-off-outline
            name: Switch to dark mode
          primary: teal
          accent: amber
        - scheme: slate
          toggle:
              icon: material/toggle-switch
              name: Switch to light mode
          primary: teal
          accent: indigo


    feature:
        tabs: true

        #font:
        #text: 'Ubuntu'
        #code: 'Ubuntu Mono'

    favicon: 'assets/images/favicon.ico'

    language: 'zh'
    icon:
        admonition:
            note: octicons/tag-16
            abstract: octicons/checklist-16
            info: octicons/info-16
            tip: octicons/squirrel-16
            success: octicons/check-16
            question: octicons/question-16
            warning: octicons/alert-16
            failure: octicons/x-circle-16
            danger: octicons/zap-16
            bug: octicons/bug-16
            example: octicons/beaker-16
            quote: octicons/quote-16


# Customization
extra:
    social:
        - icon: fontawesome/brands/github-alt
          link: https://github.com/wendaojidian

    search:
        language: 'en, de, ru'

    disqus: 'ray'


# Extensions
markdown_extensions:
    - admonition
    - codehilite:
          guess_lang: false
          linenums: false
    - toc:
          permalink: true
    - footnotes
    - meta
    - def_list
    - pymdownx.arithmatex
    - pymdownx.betterem:
          smart_enable: all
    - pymdownx.caret
    - pymdownx.critic
    - pymdownx.details
    - pymdownx.emoji:
          emoji_generator: !!python/name:pymdownx.emoji.to_png
    - pymdownx.inlinehilite
    - pymdownx.magiclink
    - pymdownx.mark
    - pymdownx.smartsymbols
    - pymdownx.superfences
    - pymdownx.tasklist:
        custom_checkbox: true
    - pymdownx.tilde
    - pymdownx.keys

extra_javascript:
    - 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_CHTML'


# Google Analytics
google_analytics:
    - "UA-156919721-1"
    - "auto"

plugins:
    - search

nav:
    - 介绍: index.md
    - java:
        - 并发:
            - java8并发任务编排器-Completable: java/并发/java8并发任务编排利器-Completable.md
        - netty:
            - netty笔记: java/netty/netty笔记-1.md
    - 读书笔记:
        - 后端技术:
            - 深入理解分布式系统: 读书笔记/后端技术/深入理解分布式系统.md
            - 代码整洁之道: 读书笔记/后端技术/代码整洁之道.md
            - 深入理解java虚拟机: 读书笔记/后端技术/深入理解java虚拟机.md
            - 计算机网络-自顶向下方法: 读书笔记/后端技术/计算机网络-自顶向下方法.md
            - 网络知识: 读书笔记/后端技术/网络知识.md
        - 投资:
            - 指数基金投资指南: 读书笔记/投资/指数基金投资指南.md
            - 经济学原理: 读书笔记/投资/经济学原理.md
    - git:
        - git开发全搞定: git.md
    - tools:
        - md命令速查: md命令速查.md
        - MKDocs: MKDocs.md
    - trace: trace.md
